export const LOADING_ALLERGIES = "[ALLERGY] LOADING_ALLERGIES";
export const LOAD_ALLERGIES_FULFILLED = "[ALLERGY] LOAD_ALLERGIES_FULFILLED";
export const LOAD_ALLERGIES_FAILED = "[ALLERGY] LOAD_ALLERGIES_FAILED";
export const LOAD_ALLERGIES = "[ALLERGY] LOAD_ALLERGIES";

export const ADDING_ALLERGY = "[ALLERGY] ADDING_ALLERGY";
export const ADD_ALLERGY_SUCCESS = "[ALLERGY] ADD_ALLERGY_SUCCESS";
export const ADD_ALLERGY_FAILED = "[ALLERGY] ADD_ALLERGY_FAILED";
export const ADD_ALLERGY = "[ALLERGY] ADD_ALLERGY";