export const LOADING_APPOINTMENTS = "[APPOINTMENT] LOADING_APPOINTMENTS";
export const LOAD_APPOINTMENTS_FULFILLED =
  "[APPOINTMENT] LOAD_APPOINTMENTS_FULFILLED";
export const LOAD_APPOINTMENTS_FAILED =
  "[APPOINTMENT] LOAD_APPOINTMENTS_FAILED";
export const LOAD_APPOINTMENTS = "[APPOINTMENT] LOAD_APPOINTMENTS";
export const REFRESH_APPOINTMENTS = "[APPOINTMENT] REFRESH_APPOINTMENTS";

export const UPDATE_APPOINTMENT_SUCCESS = "[APPOINTMENT] UPDATE_APPOINTMENT_SUCCESS";
export const UPDATE_APPOINTMENT_FAILED = "[APPOINTMENT] UPDATE_APPOINTMENT_FAILED";
export const UPDATE_APPOINTMENT = "[APPOINTMENT] UPDATE_APPOINTMENT";
export const UPDATING_APPOINTMENT = "[APPOINTMENT] UPDATING_APPOINTMENT";

export const CANCEL_APPOINTMENT_SUCCESS = "[APPOINTMENT] CANCEL_APPOINTMENT_SUCCESS";
export const CANCEL_APPOINTMENT_FAILED = "[APPOINTMENT] CANCEL_APPOINTMENT_FAILED";
export const CANCEL_APPOINTMENT = "[APPOINTMENT] CANCEL_APPOINTMENT";
export const CANCELING_APPOINTMENT = "[APPOINTMENT] CANCELING_APPOINTMENT";