export const TOGGLE_MODAL = "[BOOKING_MODAL] TOGGLE_MODAL";
export const CLOSE_MODAL = "[BOOKING_MODAL] CLOSE_MODAL";

export const LOAD_BOOK_APPOINTMENT_FAILED = "[APPOINTMENT] LOAD_BOOK_APPOINTMENT_FAILED";
export const LOAD_BOOK_APPOINTMENT = "[APPOINTMENT] LOAD_BOOK_APPOINTMENT";
export const LOADING_BOOK_APPOINTMENT = "[APPOINTMENT] LOADING_BOOK_APPOINTMENT";
export const LOAD_BOOK_APPOINTMENT_FULFILLED = "[APPOINTMENT] LOAD_BOOK_APPOINTMENT_FULFILLED";

export const BOOK_APPOINTMENT = "[BOOKING_MODAL] BOOK_APPOINTMENT";
export const BOOKING_APPOINTMENT = "[BOOKING_MODAL] BOOKING_APPOINTMENT";
export const BOOK_APPOINTMENT_SUCCESS = "[BOOKING_MODAL] BOOK_APPOINTMENT_SUCCESS";
export const BOOK_APPOINTMENT_FAILED = "[BOOKING_MODAL] BOOK_APPOINTMENT_FAILED";
