export const LOADING_FAMILYILLNESSLIST = "[FAMILY_ILLNESS_LIST] LOADING_FAMILYILLNESSLIST";
export const LOAD_FAMILYILLNESSLIST_FULFILLED = "[FAMILY_ILLNESS_LIST] LOAD_FAMILYILLNESSLIST_FULFILLED";
export const LOAD_FAMILYILLNESSLIST_FAILED = "[FAMILY_ILLNESS_LIST] LOAD_FAMILYILLNESSLIST_FAILED";
export const LOAD_FAMILYILLNESSLIST = "[FAMILY_ILLNESS_LIST] LOAD_FAMILYILLNESSLIST";

export const ADDING = "[ADD_FAMILY_ILLNESS] ADDING";
export const ADD_SUCCESS = "[ADD_FAMILY_ILLNESS] ADD_SUCCESS";
export const ADD_FAILED = "[ADD_FAMILY_ILLNESS] ADD_FAILED";
export const ADD = "[ADD_FAMILY_ILLNESS] ADD";