export const LOADING_NEXTFEED = "[FEED_DETAIL] LOADING_NEXTFEED";
export const LOAD_NEXTFEED_FULFILLED = "[FEED_DETAIL] LOAD_NEXTFEED_FULFILLED";
export const LOAD_NEXTFEED_FAILED = "[FEED_DETAIL] LOAD_NEXTFEED_FAILED";
export const LOAD_NEXTFEED = "[FEED_DETAIL] LOAD_NEXTFEED";

export const LOADING_DETAIL = "[FEED_DETAIL] LOADING_DETAIL";
export const LOAD_DETAIL_FULFILLED = "[FEED_DETAIL] LOAD_DETAIL_FULFILLED";
export const LOAD_DETAIL_FAILED = "[FEED_DETAIL] LOAD_DETAIL_FAILED";
export const LOAD_DETAIL = "[FEED_DETAIL] LOAD_DETAIL";

export const BOOKMARKING = "[FEED_DETAIL] BOOKMARKING";
export const TOGGLE_BOOKMARK_FULFILLED =
  "[FEED_DETAIL] TOGGLE_BOOKMARK_FULFILLED";
export const TOGGLE_BOOKMARK_FAILED = "[FEED_DETAIL] TOGGLE_BOOKMARK_FAILED";
export const TOGGLE_BOOKMARK = "[FEED_DETAIL] TOGGLE_BOOKMARK";

export const RELOAD_COMMENTS = "[FEED_DETAIL] RELOAD_COMMENTS";
export const RELOAD_COMMENTS_FULFILLED =
  "[FEED_DETAIL] RELOAD_COMMENTS_FULFILLED";
export const RELOAD_COMMENTS_FAILED = "[FEED_DETAIL] RELOAD_COMMENTS_FAILED";
