export const LOADING_CATEGORIES = "[TAB_HOME] LOADING_CATEGORIES";
export const LOAD_CATEGORIES_FULFILLED = "[TAB_HOME] LOAD_CATEGORIES_FULFILLED";
export const LOAD_CATEGORIES_FAILED = "[TAB_HOME] LOAD_CATEGORIES_FAILED";
export const LOAD_CATEGORIES = "[TAB_HOME] LOAD_CATEGORIES";

export const LOADING_ARTICLES = "[TAB_HOME] LOADING_ARTICLES";
export const LOAD_ARTICLES_FULFILLED = "[TAB_HOME] LOAD_ARTICLES_FULFILLED";
export const LOAD_ARTICLES_FAILED = "[TAB_HOME] LOAD_ARTICLES_FAILED";
export const LOAD_ARTICLES = "[TAB_HOME] LOAD_ARTICLES";

export const TOGGLE_BOOKMARK = "[TAB_HOME] TOGGLE_BOOKMARK";

export const TOGGLE_TABBAR = "[COMMON] TOGGLE_TABBAR";