export const LOADING_INSURANCES = "[INSURANCE] LOADING_ALLERGIES";
export const LOAD_INSURANCES_FULFILLED = "[INSURANCE] LOAD_INSURANCES_FULFILLED";
export const LOAD_INSURANCES_FAILED = "[INSURANCE] LOAD_INSURANCES_FAILED";
export const LOAD_INSURANCES = "[INSURANCE] LOAD_INSURANCES";