export const LOADING_MEDICAL = "[MEDICAL_HISTORY] LOADING_MEDICAL";
export const LOAD_MEDICAL_FULFILLED = "[MEDICAL_HISTORY] LOAD_MEDICAL_FULFILLED";
export const LOAD_MEDICAL_FAILED = "[MEDICAL_HISTORY] LOAD_MEDICAL_FAILED";
export const LOAD_MEDICAL = "[MEDICAL_HISTORY] LOAD_MEDICAL";

export const SAVE_MEDICAL = "[ADD_MEDICAL] SAVE_MEDICAL";
export const SAVING_MEDICAL = "[ADD_MEDICAL] SAVING_MEDICAL";
export const SAVE_MEDICAL_SUCCESS = "[ADD_MEDICAL] SAVE_MEDICAL_SUCCESS";
export const SAVE_MEDICAL_FAILED = "[ADD_MEDICAL] SAVE_MEDICAL_FAILED";
export const SAVE_MEDICAL_TEMP = "[ADD_MEDICAL] SAVE_MEDICAL_TEMP";

export const LOAD_MEDICAL_DETAIL = "[MEDICAL_DETAIL] LOAD_MEDICAL_DETAIL";
export const LOADING_MEDICAL_DETAIL = "[MEDICAL_DETAIL] LOADING_MEDICAL_DETAIL";
export const LOAD_MEDICAL_DETAIL_SUCCESS = "[MEDICAL_DETAIL] LOAD_MEDICAL_DETAIL_SUCCESS";
export const LOAD_MEDICAL_DETAIL_FAILED = "[MEDICAL_DETAIL] LOAD_MEDICAL_DETAIL_FAILED";
export const LOAD_IMAGE_SUCCESS = "[MEDICAL_DETAIL] LOAD_IMAGE_SUCCESS";
export const LOAD_IMAGE_FAILED = "[MEDICAL_DETAIL] LOAD_IMAGE_FAILED";
export const RESET_MEDICAL_DETAIL = "[MEDICAL_DETAIL] RESET_MEDICAL_DETAIL";