export const LOADING_PAYMENTTHISTORIES = "[PAYMENTHISTORY] LOADING_PAYMENTHISTORIES";
export const LOAD_PAYMENTHISTORIES_FULFILLED = "[PAYMENTHISTORY] LOAD_PAYMENTHISTORIES_FULFILLED";
export const LOAD_PAYMENTHISTORIES_FAILED = "[PAYMENTHISTORY] LOAD_PAYMENTHISTORIES_FAILED";
export const LOAD_PAYMENTHISTORIES = "[PAYMENTHISTORY] LOAD_PAYMENTHISTORIES";