export const LOADING_PRESCRIPTIONHISTORIES = "[PRESCRIPTIONHISTORY] LOADING_PRESCRIPTIONHISTORIES";
export const LOAD_PRESCRIPTIONHISTORIES_FULFILLED = "[PRESCRIPTIONHISTORY] LOAD_PRESCRIPTIONHISTORIES_FULFILLED";
export const LOAD_PRESCRIPTIONHISTORIES_FAILED = "[PRESCRIPTIONHISTORY] LOAD_PRESCRIPTIONHISTORIES_FAILED";
export const LOAD_PRESCRIPTIONHISTORIES = "[PRESCRIPTIONHISTORY] LOAD_PRESCRIPTIONHISTORIES";

export const BUYING_PRESCRIPTION = "[PRESCRIPTIONHISTORY] BUYING_PRESCRIPTION";
export const BUY_PRESCRIPTION = "[PRESCRIPTIONHISTORY] BUY_PRESCRIPTION";
export const BUY_PRESCRIPTION_SUCCESS = "[PRESCRIPTIONHISTORY] BUY_PRESCRIPTION_SUCCESS";
export const BUY_PRESCRIPTION_FAILED = "[PRESCRIPTIONHISTORY] BUY_PRESCRIPTION_FAILED";

export const LOADING_RECENTDRUGSTORE = "[DRUGSTORE] LOADING_RECENTDRUGSTORE";
export const LOAD_RECENTDRUGSTORE = "[DRUGSTORE] LOAD_RECENTDRUGSTORE";
export const LOAD_RECENTDRUGSTORE_SUCCESS = "[DRUGSTORE] LOAD_RECENTDRUGSTORE_SUCCESS";
export const LOAD_RECENTDRUGSTORE_FAILED = "[DRUGSTORE] LOAD_RECENTDRUGSTORE_FAILED";

export const TOOGLE_BUY_PRESCRIPTION_MODAL = "[PRESCRIPTIONHISTORY] BUY_PRESCRIPTION_MODAL";

export const FIND_LIST_DRUGSRORE = "[DRUGSTORE] FIND_LIST_DRUGSRORE";
export const FINDING_LIST_DRUGSRORE = "[DRUGSTORE] FINDING_LIST_DRUGSRORE";
export const FIND_LIST_DRUGSRORE_SUCCESS = "[DRUGSTORE] FIND_LIST_DRUGSRORE_SUCCESS";
export const FIND_LIST_DRUGSRORE_FAILED = "[DRUGSTORE] FIND_LIST_DRUGSRORE_FAILED";
