export const LOADING_SAVED = "[SAVED] LOADING_SAVED";
export const LOAD_SAVED_FULFILLED = "[SAVED] LOAD_SAVED_FULFILLED";
export const LOAD_SAVED_FAILED = "[SAVED] LOAD_SAVED_FAILED";
export const LOAD_SAVED = "[SAVED] LOAD_SAVED";
