export const SEARCH_REQUESTED = "[SEARCH] SEARCH_REQUESTED";
export const SEARCH_MORE_REQUESTED = "[SEARCH] SEARCH_MORE_REQUESTED";
export const SEARCH_FULFILLED = "[SEARCH] SEARCH_FULFILLED";
export const SEARCH_FAILED = "[SEARCH] SEARCH_FAILED";
export const SEARCH_TYPE_CHANGED = "[SEARCH] SEARCH_TYPE_CHANGED";
