export const LOADING_SEARCH_DETAIL = "[SEARCH_DETAIL] LOADING_SEARCH_DETAIL";
export const LOAD_SEARCH_DETAIL_FULFILLED = "[SEARCH_DETAIL] LOAD_SEARCH_DETAIL_FULFILLED";
export const LOAD_SEARCH_DETAIL_FAILED = "[SEARCH_DETAIL] LOAD_SEARCH_DETAIL_FAILED";
export const LOAD_SEARCH_DETAIL = "[SEARCH_DETAIL] LOAD_SEARCH_DETAIL";

export const SEARCH_DETAIL_TOGGLE_BOOKMARKING = "[SEARCH_DETAIL] SEARCH_DETAIL_TOGGLE_BOOKMARKING";
export const SEARCH_DETAIL_TOGGLE_BOOKMARK_FULFILLED =
  "[SEARCH_DETAIL] SEARCH_DETAIL_TOGGLE_BOOKMARK_FULFILLED";
export const SEARCH_DETAIL_TOGGLE_BOOKMARK_FAILED = "[SEARCH_DETAIL] SEARCH_DETAIL_TOGGLE_BOOKMARK_FAILED";
export const SEARCH_DETAIL_TOGGLE_BOOKMARK = "[SEARCH_DETAIL] SEARCH_DETAIL_TOGGLE_BOOKMARK";