export const LOAD_SYMPTOM = "[SYMPTOM] LOAD_SYMPTOM";
export const LOADING_SYMPTOM = "[SYMPTOM] LOADING_SYMPTOM";
export const LOAD_SYMPTOM_FULFILLED = "[SYMPTOM] LOAD_SYMPTOM_FULFILLED";
export const LOAD_SYMPTOM_FAILED = "[SYMPTOM] LOAD_SYMPTOM_FAILED";