export const LOADING_TESTHISTORIES = "[TESTHISTORY] LOADING_TESTHISTORIES";
export const LOAD_TESTHISTORIES_FULFILLED = "[TESTHISTORY] LOAD_TESTHISTORIES_FULFILLED";
export const LOAD_TESTHISTORIES_FAILED = "[TESTHISTORY] LOAD_TESTHISTORIES_FAILED";
export const LOAD_TESTHISTORIES = "[TESTHISTORY] LOAD_TESTHISTORIES";