export const LOADING_VACCINATIONHISTORIES = "[VACCINATIONHISTORY] LOADING_VACCINATIONHISTORIES";
export const LOAD_VACCINATIONHISTORIES_FULFILLED = "[VACCINATIONHISTORY] LOAD_VACCINATIONHISTORIES_FULFILLED";
export const LOAD_VACCINATIONHISTORIES_FAILED = "[VACCINATIONHISTORY] LOAD_VACCINATIONHISTORIES_FAILED";
export const LOAD_VACCINATIONHISTORIES = "[VACCINATIONHISTORY] LOAD_VACCINATIONHISTORIES";

export const ADDING_VACCINATION = "[ADD_VACCINATION] ADDING_VACCINATION";
export const ADD_VACCINATION_SUCCESS = "[ADD_VACCINATION] ADD_VACCINATION_SUCCESS";
export const ADD_VACCINATION_FAILED = "[ADD_VACCINATION] ADD_VACCINATION_FAILED";
export const ADD_VACCINATION = "[ADD_VACCINATION] ADD_VACCINATION";
